//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MikeAutoRun
{
    using System;
    using System.Collections.Generic;
    
    public partial class CSSPItem
    {
        public CSSPItem()
        {
            this.AppTasks = new HashSet<AppTask>();
            this.MikeScenarios = new HashSet<MikeScenario>();
        }
    
        public int CSSPItemID { get; set; }
        public int CSSPItemTypeID { get; set; }
        public System.DateTime LastModifiedDate { get; set; }
        public int ModifiedByID { get; set; }
        public bool IsActive { get; set; }
    
        public virtual ICollection<AppTask> AppTasks { get; set; }
        public virtual ICollection<MikeScenario> MikeScenarios { get; set; }
    }
}
