//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MikeAutoRun
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CSSPAppDB2Entities : DbContext
    {
        public CSSPAppDB2Entities()
            : base("name=CSSPAppDB2Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<AppTask> AppTasks { get; set; }
        public DbSet<CSSPFile> CSSPFiles { get; set; }
        public DbSet<CSSPItem> CSSPItems { get; set; }
        public DbSet<MikeScenarioFile> MikeScenarioFiles { get; set; }
        public DbSet<MikeScenario> MikeScenarios { get; set; }
    }
}
